services:
  rabbitmq:
    image: rabbitmq:4.1.4-management
    container_name: vetcore_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vetcore-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  notifications-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vetcore_notifications
    restart: always
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - vetcore-network

networks:
  vetcore-network:
    driver: bridge
